### ISSUE TITLE
Add Emacs "support"

### ISSUE THREAD

**Issue by jloow** [cproctor/qualitative-coding#12]
"Support" for Emacs (i.e. opening the files in a similar manner to how they are opened in Vim) can be added by by modifying the run command:

```python
run(["emacs", "-Q", "--eval",
             "(progn (find-file \"{}\") (split-window-right) (other-window 1) (find-file \"{}\") (scroll-all-mode))".format(*files)])
```

This opens the corpus file and the code file in two separate windows, with scrolling synced between the two windows.

The exact flags to pass can be discussed (`-Q` loads Emacs without a config file, for example; `-nw` opens Emacs in a terminal) as can whether to start a new instance of Emacs or if one should use `emacsclient` instead.

Emacs doesn't accept Windows-style paths, so for this to work under Windows, the file paths need to be converted to posix-style paths. In my fork, I solved this by calling `open_editor` as such:  `self.open_editor([f.as_posix(), code_file.as_posix()])`.

**Comment by cproctor** [comment]
Hi, sorry I didn't see this until now--thanks for the contribution! I'll test it out and add it to the next release.

**Comment by jloow** [comment]
Looking at  #16, with the editor option, I'm thinking that could be a suitable implementation.

**Comment by cproctor** [comment]
Merging this into #24.
