### ISSUE TITLE
JOSS: Community Guidelines

### ISSUE THREAD

**Issue by cmaimone** [cproctor/qualitative-coding#45]
https://github.com/openjournals/joss-reviews/issues/7031 - Community Guidelines

Suggestions: 

- In the documentation https://qualitative-coding.readthedocs.io/en/latest/manuscript.html#contributing, link to https://www.contributor-covenant.org/
- Add a CONTRIBUTING file to the repo, so that people see the guidelines when going to the issue page
<img width="1347" alt="Screenshot 2024-07-31 at 11 30 01 AM" src="https://github.com/user-attachments/assets/3dcfdb6e-a7d8-4cdf-aa04-3f01717e589a">

Needed:

- Clearer information on how someone contributes to the software, not just submit a bug report (do you want them to submit PRs?)
- Clearer information on getting support (create an issue?  email you?)

**Comment by cproctor** [comment]
Thanks! I appreciate this feedback, and should be able to address them shortly.

**Comment by cproctor** [comment]
I have accepted all the suggestions and updated the repo accordingly. Thanks!
