### ISSUE TITLE
Issue importing demo

### ISSUE THREAD

**Issue by cmaimone** [cproctor/qualitative-coding#46]
Re: https://github.com/openjournals/joss-reviews/issues/7031

I followed the commands at https://qualitative-coding.readthedocs.io/en/latest/manuscript.html#exploring-an-existing-project but ran into an error when trying to init the project:

```
/Users/christina/Desktop/qc_demo % qc init --import ../demo.qdpx
../demo.qdpx is not a zipfile
```

**Comment by cproctor** [comment]
Thanks! I'm working now on reproducing this error, then will hopefully fix it.

**Comment by cproctor** [comment]
It's an issue with the `curl` command--the file that gets downloaded is actually a html file (change the extension to `.html` and you can open it in the browser). Working on the correct command to fetch the binary zip file.

**Comment by cproctor** [comment]
I decided to host the demo project on an external URL rather than as part of the repo. I've updated the docs with the new URL for the demo project (https://computationalliteracies.net/people/chris/demo.qdpx), and tested the tutorial workflow to confirm that it's working. Thanks!
