### ISSUE TITLE
Error - maybe with text editor?

### ISSUE THREAD

**Issue by cmaimone** [cproctor/qualitative-coding#54]
Attempting to start a coding session.  I have one text document imported in my project.  I have Visual Studio Code installed on my system, but not running/open.  I get this error: 

```
(base) /Users/christina/Desktop/qc_project % qc code christina2
An incomplete coding session exists. Run qc code --recover to recover this coding session or qc code --abandon to abandon it.
```

The very first time I ran this, I got some slight variation on the error message, but now I'm getting this, even if I switch the user name. Not sure 1) why I got the error originally, and 2) what to do now, since it seems stuck on this.

Relatedly, the documentation says I can use a different editor if I want, but I didn't see how to do this (I might have missed it).  For example, if I want to use BBEdit, or RStudio, how do I set that?

re: https://github.com/openjournals/joss-reviews/issues/7031

**Comment by cproctor** [comment]
I have substantially expanded the documentation in response to these thoughtful points:
- The prerequisites section now lists Sublime Text and its Scroll Sync extension, which is helpful. 
- A note in the vignette explains how to align the document and the coding file when using VS Code. 
- Regarding editor support, I have added a section documenting all the settings; the [section on editors](https://qualitative-coding.readthedocs.io/en/latest/manuscript.html#editor) explains how to specify additional editors. 

In this specific situation, I'm guessing that maybe you ran `qc code` once before you had VS Code installed, so the invocation failed and left the project with an open coding session. I would expect that `qc code christina2 --abandon` would get you back to a clean state. Please let me know if the issue still appears.
