### ISSUE TITLE
qc memo requires coder argument

### ISSUE THREAD

**Issue by cmaimone** [cproctor/qualitative-coding#61]
https://qualitative-coding.readthedocs.io/en/latest/manuscript.html#memo - this isn't a valid example.  The command requires that the coder be specified.  

I also can't list memos except for a specific coder - I can't see all of them?

```
% qc memo -l                                          
Usage: qc memo [OPTIONS] CODER
Try 'qc memo --help' for help.

Error: Missing argument 'CODER'.
```

re: https://github.com/openjournals/joss-reviews/issues/7031

**Comment by cproctor** [comment]
Oops. Thanks! Now fixed.

**Comment by cproctor** [comment]
I agree, it could be useful to see all memos together, however listing memos is currently implemented as a flag on the `memo` command (e.g. `qc memo chris --list`), so the coder is required. I could break listing out as a separate command (e.g. `qc memo list --coder chris` or `qc memo list`), but this would present ambiguity (e.g. is`qc memo list` a request to list memos or a request to write a memo with coder named "list"?

I could also add an `--all` flag to the current command, but it feels clumsy to specify a coder and then to essentially follow that with "oh wait actually show me everyone's memos."

As I don't see an elegant solution and the use case doesn't feel urgent, I'm inclined not to make a change. What do you think?

**Comment by cmaimone** [comment]
I'm not sure how you're using the memo files in practice, so I don't know what functionality would be best.  From an outside perspective, I would find it awkward to have to look at essentially individual memo files - I'd see that as more of just personal memos then instead of a team coordination tool.  Maybe that's what it's intended to be?
