### ISSUE TITLE
qc init minor usability issues

### ISSUE THREAD

**Issue by SamHames** [cproctor/qualitative-coding#64]
I was working through [create new project docs](https://qualitative-coding.readthedocs.io/en/latest/manuscript.html#create-a-new-project) and ran into a couple of minor issues while experimenting:

1. I missed the `-y` flag for `qc init`, which means that later commands like `qc corpus import` would fail because the necessary files and folders hadn't been created. I think it would be less surprising if `qc init` created the default folder structure as you already have the `--settings` option for the customised case.
2. Running `qc init -s {settings_file_in_another_directory}` doesn't fully initialise the project as the settings file isn't copied - it might be better to either copy the settings file to the directory being initialised or provide a warning.

**Comment by cproctor** [comment]
Thanks for this thoughtful feedback--I agree with you on both points and have addressed them in 1.5.4 (in code, docs, and tests). 

1. After some reflection, I agree with you. Now, `qc init` creates the settings file if necessary, reads it, and creates project assets as specified. The `--write-settings-file` (`-w`) flag can be used to create a settings file without creating project assets, for users who want to modify settings before initialization.  
2. This should certainly work as you describe, and was an easy fix.
