### ISSUE TITLE
anonymize and overlapping names

### ISSUE THREAD

**Issue by cmaimone** [cproctor/qualitative-coding#68]
When the anonymize function creates anonymized versions of the documents, it does not handle names that may have overlap in them correctly.  For example, in my corpus, it identified:
Christina: Person_1
Christina M: Person_3

In the anonymized version of the document with "Christina M" in it, it replaced just Christina: "Person_1 M..."

**Comment by cproctor** [comment]
This is functioning as designed, although I can see how in this situation the results might be surprising. It's a simple find-and-replace algorithm, iterating through the terms in the key file. So "Christina" got replaced with "Person_1" and then "Christina M" didn't match. 

The most straightforward way of getting expected results using the current system would be to move "Christina M" above "Christina." This situation *could* be handled by organizing keys into a graph of substrings, and replacing the longest key strings first. I want to think about whether this might have other, more confusing side effects. 

I'll either add a note to the documentation cautioning users about this, or will adopt the substring strategy.

**Comment by cproctor** [comment]
I agree that the issue pointed out here should not happen, and have updated the command (with tests) in 1.6.0, the JOSS release version. Thanks!
